#server configurations
server:
  host: "localhost"
  port: 1729

#database credentials
database:
  mysql:
    host: "localhost"
    port: "3306"
    user: "root"
    pass: "Admin@123"
    net: "tcp"
    dbname: "flightBooking"